services:
  - type: web
    name: visitor-tracker
    runtime: node
    repo: https://github.com/kgjhgdgjhk/visitor-tracker
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production